version: '2'

services:
  ghost:
    image: ghost
    volumes:
      - ./content:/usr/src/ghost/content
      - ./config:/var/lib/ghost
    ports:
     - "2368:2368"
    restart: always

  buster:
    image: raccoony/buster
    links:
      - ghost
    depends_on:
      - ghost
    env_file: .env
    environment:
      - EMAIL=raccoonyy@gmail.com
      - LOGNAME=raccoony
      - PUBLIC_URL=${GITHUB_ID}.github.io
      - GIT_REPO=git@github.com:${GITHUB_ID}/${GITHUB_ID}.github.com.git
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports:
      - "9000:9000"
